/// Flutter icons MyFlutterApp
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Modern Pictograms, Copyright (c) 2012 by John Caserta. All rights reserved.
///         Author:    John Caserta
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://thedesignoffice.org/project/modern-pictograms/
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';
  static const String _kFontPkg = null;

  static const IconData call = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cast = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData assistant_photo = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData attach_file = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bluetooth_disabled = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bluetooth_searching = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData border_vertical = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData branding_watermark = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData business_center = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cached = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData card_membership = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData card_travel = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData class_icon = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clear = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData access_alarm = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData access_alarms = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData access_time = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_to_queue = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData adjust = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData airline_seat_flat = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_alert = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_box = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_circle = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_circle_outline = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_location = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData airport_shuttle = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alarm = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alarm_add = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alarm_off = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alarm_on = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData aspect_ratio = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData assessment = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData assignment = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData assignment_ind = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData assignment_late = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData battery_full = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData battery_std = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData battery_unknown = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData beach_access = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData beenhere = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData border_clear = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData border_color = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData border_horizontal = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData border_inner = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData border_left = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData brightness_low = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData brightness_medium = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData broken_image = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData brush = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bubble_chart = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData call_to_action = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera = IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera_alt = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera_enhance = IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera_front = IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clock = IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData network_locked = IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData more_horiz = IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData network_wifi = IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData more_vert = IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check = IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check_circle = IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bullhorn = IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData categories = IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData repeat_grid_4 = IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData money = IconData(0xf0d6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData euro = IconData(0xf153, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData question_circle_o = IconData(0xf29c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
